name: Release

on:
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "::warning::Lockfile tidak ada. Membuat yang baru..."
            pnpm install --lockfile-only
      
            git config --global user.email "hub@erdev.biz.id"
            git config --global user.name "ErBots"
      
            git add pnpm-lock.yaml
            git commit -m "chore: add lockfile [skip ci]"
            git push
          fi
      
          pnpm install --frozen-lockfile

      - name: Validate package.json
        run: |
          if ! jq empty package.json; then
            echo "✅ package.json valid"
          else
            echo "❌ Invalid package.json"
            exit 1
          fi

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Publish to NPM
        run: |
          pnpm publish --access public --no-git-checks

          CURRENT_VERSION=$(jq -r .version package.json)
          pnpm exec -c "npm deprecate $(jq -r .name package.json)@\"<${CURRENT_VERSION}\" \"This version is deprecated. Please upgrade to ${CURRENT_VERSION}.\""
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
          NPM_CONFIG_PROVENANCE: true